//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arma.Studio.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string App_GenericOperationFailedMessageBox_Body {
            get {
                return ResourceManager.GetString("App_GenericOperationFailedMessageBox_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string App_GenericOperationFailedMessageBox_Title {
            get {
                return ResourceManager.GetString("App_GenericOperationFailedMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma.Studio.
        /// </summary>
        public static string ArmaStudio {
            get {
                return ResourceManager.GetString("ArmaStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollapseAll.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration. Using empty..
        /// </summary>
        public static string Configuration_ExceptionDuringLoad {
            get {
                return ResourceManager.GetString("Configuration_ExceptionDuringLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Debugger_Attach {
            get {
                return ResourceManager.GetString("Debugger_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Debugger_Continue {
            get {
                return ResourceManager.GetString("Debugger_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Debugger_Pause_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Pause_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Debugger_Start {
            get {
                return ResourceManager.GetString("Debugger_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Into.
        /// </summary>
        public static string Debugger_StepInto_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepInto_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Out.
        /// </summary>
        public static string Debugger_StepOut_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Over.
        /// </summary>
        public static string Debugger_StepOver_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOver_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Debugger_Stop_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpandAll.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Plugin {0}.
        /// </summary>
        public static string FailedToLoadPlugin_Body {
            get {
                return ResourceManager.GetString("FailedToLoadPlugin_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugin has Failed..
        /// </summary>
        public static string FailedToLoadPlugin_Title {
            get {
                return ResourceManager.GetString("FailedToLoadPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_Menu_File_New {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainWindow_Menu_File_Quit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchorables.
        /// </summary>
        public static string MainWindow_Menu_View_Anchorables {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View_Anchorables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Plugin &apos;{0}&apos;.
        /// </summary>
        public static string SplashScreen_InitializingPlugin_0Name {
            get {
                return ResourceManager.GetString("SplashScreen_InitializingPlugin_0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Plugins.
        /// </summary>
        public static string SplashScreen_LoadingPlugins {
            get {
                return ResourceManager.GetString("SplashScreen_LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Loggers.
        /// </summary>
        public static string SplashScreen_PreparingLoggers {
            get {
                return ResourceManager.GetString("SplashScreen_PreparingLoggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing User-Interface.
        /// </summary>
        public static string SplashScreen_PreparingUserInterface {
            get {
                return ResourceManager.GetString("SplashScreen_PreparingUserInterface", resourceCulture);
            }
        }
    }
}
