//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arma.Studio.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proudly made by:.
        /// </summary>
        public static string AboutDialog_ContributorsNote {
            get {
                return ResourceManager.GetString("AboutDialog_ContributorsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy release info to clipboard.
        /// </summary>
        public static string AboutDialog_CopyReleaseInfo {
            get {
                return ResourceManager.GetString("AboutDialog_CopyReleaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma.Studio.
        /// </summary>
        public static string AboutDialog_Header {
            get {
                return ResourceManager.GetString("AboutDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins in use.
        /// </summary>
        public static string AboutDialog_LoadedPlugins {
            get {
                return ResourceManager.GetString("AboutDialog_LoadedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Arma.Studio.
        /// </summary>
        public static string AboutDialog_Title {
            get {
                return ResourceManager.GetString("AboutDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string App_GenericOperationFailedMessageBox_Body {
            get {
                return ResourceManager.GetString("App_GenericOperationFailedMessageBox_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string App_GenericOperationFailedMessageBox_Title {
            get {
                return ResourceManager.GetString("App_GenericOperationFailedMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma.Studio.
        /// </summary>
        public static string ArmaStudio {
            get {
                return ResourceManager.GetString("ArmaStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration. Using empty..
        /// </summary>
        public static string Configuration_ExceptionDuringLoad {
            get {
                return ResourceManager.GetString("Configuration_ExceptionDuringLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string Debugger_Attach {
            get {
                return ResourceManager.GetString("Debugger_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Debugger_Continue {
            get {
                return ResourceManager.GetString("Debugger_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next instruction.
        /// </summary>
        public static string Debugger_Next_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Next_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Debugger_Pause_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Pause_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Debugger_Start {
            get {
                return ResourceManager.GetString("Debugger_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Into.
        /// </summary>
        public static string Debugger_StepInto_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepInto_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Out.
        /// </summary>
        public static string Debugger_StepOut_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-Over.
        /// </summary>
        public static string Debugger_StepOver_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOver_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Debugger_Stop_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load plugin {0}.
        /// </summary>
        public static string FailedToLoadPlugin_Body {
            get {
                return ResourceManager.GetString("FailedToLoadPlugin_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugin has failed..
        /// </summary>
        public static string FailedToLoadPlugin_Title {
            get {
                return ResourceManager.GetString("FailedToLoadPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restore a window with the type:
        ///&apos;{0}&apos;.
        /// </summary>
        public static string MainWindow_FailedToLoad_Body_0typestring {
            get {
                return ResourceManager.GetString("MainWindow_FailedToLoad_Body_0typestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Not Found..
        /// </summary>
        public static string MainWindow_FailedToLoad_Caption {
            get {
                return ResourceManager.GetString("MainWindow_FailedToLoad_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Menu_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_Menu_File_New {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainWindow_Menu_File_Quit {
            get {
                return ResourceManager.GetString("MainWindow_Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainWindow_Menu_Help {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_Menu_Help_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update &amp; Error Reporting Settings.
        /// </summary>
        public static string MainWindow_Menu_Help_UpdateAndErrorReportingSettings {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Help_UpdateAndErrorReportingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchorables.
        /// </summary>
        public static string MainWindow_Menu_View_Anchorables {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View_Anchorables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more changes you made require a restart. Do you want to restart now?.
        /// </summary>
        public static string MainWindow_RestartRequired_Body {
            get {
                return ResourceManager.GetString("MainWindow_RestartRequired_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string MainWindow_RestartRequired_Caption {
            get {
                return ResourceManager.GetString("MainWindow_RestartRequired_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available for ArmA.Studio.
        ///Do you want to update now?.
        /// </summary>
        public static string SoftwareUpdateAvailable_Body {
            get {
                return ResourceManager.GetString("SoftwareUpdateAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update available.
        /// </summary>
        public static string SoftwareUpdateAvailable_Caption {
            get {
                return ResourceManager.GetString("SoftwareUpdateAvailable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string SplashScreen_CheckingForUpdates {
            get {
                return ResourceManager.GetString("SplashScreen_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Plugin &apos;{0}&apos;.
        /// </summary>
        public static string SplashScreen_InitializingPlugin_0Name {
            get {
                return ResourceManager.GetString("SplashScreen_InitializingPlugin_0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugins.
        /// </summary>
        public static string SplashScreen_LoadingPlugins {
            get {
                return ResourceManager.GetString("SplashScreen_LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing loggers.
        /// </summary>
        public static string SplashScreen_PreparingLoggers {
            get {
                return ResourceManager.GetString("SplashScreen_PreparingLoggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing user-interface.
        /// </summary>
        public static string SplashScreen_PreparingUserInterface {
            get {
                return ResourceManager.GetString("SplashScreen_PreparingUserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string SplashScreen_UpdateAvailable {
            get {
                return ResourceManager.GetString("SplashScreen_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        public static string UpdateDialog_Downloading_0name {
            get {
                return ResourceManager.GetString("UpdateDialog_Downloading_0name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Update.
        /// </summary>
        public static string UpdateDialog_InstallUpdate {
            get {
                return ResourceManager.GetString("UpdateDialog_InstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deflating update.
        /// </summary>
        public static string UpdateDialog_Unzipping {
            get {
                return ResourceManager.GetString("UpdateDialog_Unzipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        public static string UpdateDialog_Updating_0name {
            get {
                return ResourceManager.GetString("UpdateDialog_Updating_0name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Account Name.
        /// </summary>
        public static string UserIdentificationDialog_Discord {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reporting.
        /// </summary>
        public static string UserIdentificationDialog_ErrorReporting {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_ErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma.Studio is supporting automatic updates &amp; error reporting.
        ///This window is to allow you to change what data is shared during error reporting and offers you a way to opt out of both, error reporting and automatic updates..
        /// </summary>
        public static string UserIdentificationDialog_Explaination {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_Explaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Identification Settings.
        /// </summary>
        public static string UserIdentificationDialog_Header {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not want to auto-report errors and auto-updates..
        /// </summary>
        public static string UserIdentificationDialog_OptOut {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_OptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you do not want auto updates and do not want to report crashes automatically?
        ///
        ///It is highly recommended to NOT opt out of theese two options..
        /// </summary>
        public static string UserIdentificationDialog_OptOut_Confirmation_Body {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_OptOut_Confirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string UserIdentificationDialog_OptOut_Confirmation_Caption {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_OptOut_Confirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Identification Settings.
        /// </summary>
        public static string UserIdentificationDialog_Title {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Identifier.
        /// </summary>
        public static string UserIdentificationDialog_UserIdentifier {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_UserIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user identifier to use in the error reporting tool. Mandatory for reporting..
        /// </summary>
        public static string UserIdentificationDialog_UserIdentifier_ToolTip {
            get {
                return ResourceManager.GetString("UserIdentificationDialog_UserIdentifier_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Util_Redo_Tooltip {
            get {
                return ResourceManager.GetString("Util_Redo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all documents and the layout.
        /// </summary>
        public static string Util_SaveAllDocuments_Tooltip {
            get {
                return ResourceManager.GetString("Util_SaveAllDocuments_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current document.
        /// </summary>
        public static string Util_SaveDocument_Tooltip {
            get {
                return ResourceManager.GetString("Util_SaveDocument_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Util_Undo_Tooltip {
            get {
                return ResourceManager.GetString("Util_Undo_Tooltip", resourceCulture);
            }
        }
    }
}
