//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmA.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArmA.Studio.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Proudly made by: ähnelt.
        /// </summary>
        public static string AboutDialog_ContributorsNote {
            get {
                return ResourceManager.GetString("AboutDialog_ContributorsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArmA.Studio ähnelt.
        /// </summary>
        public static string AboutDialog_Header {
            get {
                return ResourceManager.GetString("AboutDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins in use ähnelt.
        /// </summary>
        public static string AboutDialog_LoadedPlugins {
            get {
                return ResourceManager.GetString("AboutDialog_LoadedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string AboutDialog_Title {
            get {
                return ResourceManager.GetString("AboutDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Existing Project ähnelt.
        /// </summary>
        public static string AddExistingProject {
            get {
                return ResourceManager.GetString("AddExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
        /// </summary>
        public static string BreakpointEnabled {
            get {
                return ResourceManager.GetString("BreakpointEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label ähnelt.
        /// </summary>
        public static string BreakpointLabel {
            get {
                return ResourceManager.GetString("BreakpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The changes you made require a restart.
        ///Do you want to restart now? ähnelt.
        /// </summary>
        public static string ChangesRequireRestart_Body {
            get {
                return ResourceManager.GetString("ChangesRequireRestart_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart Required ähnelt.
        /// </summary>
        public static string ChangesRequireRestart_Title {
            get {
                return ResourceManager.GetString("ChangesRequireRestart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose ähnelt.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code Snippet ähnelt.
        /// </summary>
        public static string CodeSnippet {
            get {
                return ResourceManager.GetString("CodeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coloring ähnelt.
        /// </summary>
        public static string ColoringProperties {
            get {
                return ResourceManager.GetString("ColoringProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column ähnelt.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Community made utility ähnelt.
        /// </summary>
        public static string CommunityMadeUtility {
            get {
                return ResourceManager.GetString("CommunityMadeUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Condition ähnelt.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose the UI-Main config entry ähnelt.
        /// </summary>
        public static string ConfigEntrySelectorDialog_Header {
            get {
                return ResourceManager.GetString("ConfigEntrySelectorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UI-Config Selector ähnelt.
        /// </summary>
        public static string ConfigEntrySelectorDialog_Title {
            get {
                return ResourceManager.GetString("ConfigEntrySelectorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose File Type ähnelt.
        /// </summary>
        public static string CreateNewFileDialog_Header {
            get {
                return ResourceManager.GetString("CreateNewFileDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Creation Dialog ähnelt.
        /// </summary>
        public static string CreateNewFileDialog_Title {
            get {
                return ResourceManager.GetString("CreateNewFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Creation ähnelt.
        /// </summary>
        public static string CreateNewProjectDialog_Header {
            get {
                return ResourceManager.GetString("CreateNewProjectDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Creation Dialog ähnelt.
        /// </summary>
        public static string CreateNewProjectDialog_Title {
            get {
                return ResourceManager.GetString("CreateNewProjectDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Project ähnelt.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue ähnelt.
        /// </summary>
        public static string Debugger_Continue {
            get {
                return ResourceManager.GetString("Debugger_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pauses the execution wherever it currently is. ähnelt.
        /// </summary>
        public static string Debugger_Pause_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Pause_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string Debugger_Start {
            get {
                return ResourceManager.GetString("Debugger_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step into current scope ähnelt.
        /// </summary>
        public static string Debugger_StepInto_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepInto_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step out of current scope ähnelt.
        /// </summary>
        public static string Debugger_StepOut_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step over command ähnelt.
        /// </summary>
        public static string Debugger_StepOver_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOver_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detaches the debugger and stops the debugging session. ähnelt.
        /// </summary>
        public static string Debugger_Stop_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attaching the debugger failed.
        ///{0} ähnelt.
        /// </summary>
        public static string DebuggerContext_AttachFailed_Body {
            get {
                return ResourceManager.GetString("DebuggerContext_AttachFailed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debugger Attach Failed ähnelt.
        /// </summary>
        public static string DebuggerContext_AttachFailed_Title {
            get {
                return ResourceManager.GetString("DebuggerContext_AttachFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debugging features are not functional as no debugger was found. ähnelt.
        /// </summary>
        public static string DebuggerContext_NoDebuggerAvailable_Body {
            get {
                return ResourceManager.GetString("DebuggerContext_NoDebuggerAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Debugging Available ähnelt.
        /// </summary>
        public static string DebuggerContext_NoDebuggerAvailable_Title {
            get {
                return ResourceManager.GetString("DebuggerContext_NoDebuggerAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operation &apos;{0}&apos; failed to execute.
        ///{1} ähnelt.
        /// </summary>
        public static string DebuggerContext_OperationFailed_Body {
            get {
                return ResourceManager.GetString("DebuggerContext_OperationFailed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debugger Operation Failed ähnelt.
        /// </summary>
        public static string DebuggerContext_OperationFailed_Title {
            get {
                return ResourceManager.GetString("DebuggerContext_OperationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provides basic functionality to ArmA.Studio ähnelt.
        /// </summary>
        public static string DefaultPluginDescription {
            get {
                return ResourceManager.GetString("DefaultPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current document contains unsaved changes.
        ///Do you want to save before close? ähnelt.
        /// </summary>
        public static string DocumentBase_CloseSaveConfirmation_Body {
            get {
                return ResourceManager.GetString("DocumentBase_CloseSaveConfirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved Data ähnelt.
        /// </summary>
        public static string DocumentBase_CloseSaveConfirmation_Caption {
            get {
                return ResourceManager.GetString("DocumentBase_CloseSaveConfirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading {0} ähnelt.
        /// </summary>
        public static string DownloadingX {
            get {
                return ResourceManager.GetString("DownloadingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please modify the breakpoint ähnelt.
        /// </summary>
        public static string EditBreakpointDialog_Header {
            get {
                return ResourceManager.GetString("EditBreakpointDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breakpoint Editing ähnelt.
        /// </summary>
        public static string EditBreakpointDialog_Title {
            get {
                return ResourceManager.GetString("EditBreakpointDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors ähnelt.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Existing Item... ähnelt.
        /// </summary>
        public static string ExistingItem {
            get {
                return ResourceManager.GetString("ExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Name ähnelt.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &apos;{0}&apos; was not found. ähnelt.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string GeneralProperties {
            get {
                return ResourceManager.GetString("GeneralProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Current Document ähnelt.
        /// </summary>
        public static string Hotkey_SaveCurrentDocument {
            get {
                return ResourceManager.GetString("Hotkey_SaveCurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Messages ähnelt.
        /// </summary>
        public static string Infos {
            get {
                return ResourceManager.GetString("Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install Update ähnelt.
        /// </summary>
        public static string InstallUpdate {
            get {
                return ResourceManager.GetString("InstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Active ähnelt.
        /// </summary>
        public static string IsBreakpointActive {
            get {
                return ResourceManager.GetString("IsBreakpointActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string KeySearch {
            get {
                return ResourceManager.GetString("KeySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        public static string LicenseViewer_Header {
            get {
                return ResourceManager.GetString("LicenseViewer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License Viewer ähnelt.
        /// </summary>
        public static string LicenseViewer_Title {
            get {
                return ResourceManager.GetString("LicenseViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line ähnelt.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Tool ähnelt.
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        public static string MenuItem_Licenses {
            get {
                return ResourceManager.GetString("MenuItem_Licenses", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses ähnelt.
        /// </summary>
        public static string MenuItem_Wiki
        {
            get
            {
                return ResourceManager.GetString("MenuItem_Wiki", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Panels ähnelt.
        /// </summary>
        public static string MenuItem_Panels {
            get {
                return ResourceManager.GetString("MenuItem_Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string MenuItem_Properties {
            get {
                return ResourceManager.GetString("MenuItem_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        public static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string MenuItem_Save {
            get {
                return ResourceManager.GetString("MenuItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All ähnelt.
        /// </summary>
        public static string MenuItem_SaveAll {
            get {
                return ResourceManager.GetString("MenuItem_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch _Workspace ähnelt.
        /// </summary>
        public static string MenuItem_SwitchWorkspace {
            get {
                return ResourceManager.GetString("MenuItem_SwitchWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the file &apos;{0}&apos;? ähnelt.
        /// </summary>
        public static string MessageBoxDeleteFileConfirmation_Body {
            get {
                return ResourceManager.GetString("MessageBoxDeleteFileConfirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Delete Confirmation ähnelt.
        /// </summary>
        public static string MessageBoxDeleteFileConfirmation_Title {
            get {
                return ResourceManager.GetString("MessageBoxDeleteFileConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file has changed outside of the studio.
        ///Do you want to reload?
        ///Current progress will be lost. ähnelt.
        /// </summary>
        public static string MessageBoxFileChanged_Body {
            get {
                return ResourceManager.GetString("MessageBoxFileChanged_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Has Changed ähnelt.
        /// </summary>
        public static string MessageBoxFileChanged_Title {
            get {
                return ResourceManager.GetString("MessageBoxFileChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation failed with &apos;{0}&apos;
        ///{1}
        ///{2} ähnelt.
        /// </summary>
        public static string MessageBoxOperationFailed_Body {
            get {
                return ResourceManager.GetString("MessageBoxOperationFailed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation Failed ähnelt.
        /// </summary>
        public static string MessageBoxOperationFailed_Title {
            get {
                return ResourceManager.GetString("MessageBoxOperationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The path is not allowed to be at a root level. ähnelt.
        /// </summary>
        public static string MessageBoxWorkspaceCannotBeRoot_Body {
            get {
                return ResourceManager.GetString("MessageBoxWorkspaceCannotBeRoot_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Root Path Selected ähnelt.
        /// </summary>
        public static string MessageBoxWorkspaceCannotBeRoot_Title {
            get {
                return ResourceManager.GetString("MessageBoxWorkspaceCannotBeRoot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart application in order to make changes take effect.
        ///Restart now? ähnelt.
        /// </summary>
        public static string MessageDialog_PropertyChange {
            get {
                return ResourceManager.GetString("MessageDialog_PropertyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Folder ähnelt.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Item... ähnelt.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In the current document, there is no config entry available the UI-View could be generated from. ähnelt.
        /// </summary>
        public static string NoConfigPresent_Body {
            get {
                return ResourceManager.GetString("NoConfigPresent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing Config Entry ähnelt.
        /// </summary>
        public static string NoConfigPresent_Title {
            get {
                return ResourceManager.GetString("NoConfigPresent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not affiliated with Bohemia Interactive ähnelt.
        /// </summary>
        public static string NotAffiliatedWithBohemiaInteractive {
            get {
                return ResourceManager.GetString("NotAffiliatedWithBohemiaInteractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Available ähnelt.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Found ähnelt.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in File Explorer ähnelt.
        /// </summary>
        public static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear All ähnelt.
        /// </summary>
        public static string Output_ClearAllToolTip {
            get {
                return ResourceManager.GetString("Output_ClearAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Breakpoints ähnelt.
        /// </summary>
        public static string PanelDisplayName_Breakpoints {
            get {
                return ResourceManager.GetString("PanelDisplayName_Breakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Callstack ähnelt.
        /// </summary>
        public static string PanelDisplayName_CallStack {
            get {
                return ResourceManager.GetString("PanelDisplayName_CallStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error List ähnelt.
        /// </summary>
        public static string PanelDisplayName_ErrorList {
            get {
                return ResourceManager.GetString("PanelDisplayName_ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        public static string PanelDisplayName_Output {
            get {
                return ResourceManager.GetString("PanelDisplayName_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string PanelDisplayName_Properties {
            get {
                return ResourceManager.GetString("PanelDisplayName_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solution Explorer ähnelt.
        /// </summary>
        public static string PanelDisplayName_Solution {
            get {
                return ResourceManager.GetString("PanelDisplayName_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variables View ähnelt.
        /// </summary>
        public static string PanelDisplayName_VariablesView {
            get {
                return ResourceManager.GetString("PanelDisplayName_VariablesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more plugins have updates available to download. Do you want to update now? ähnelt.
        /// </summary>
        public static string PluginUpdateAvailable_Body {
            get {
                return ResourceManager.GetString("PluginUpdateAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin updates available ähnelt.
        /// </summary>
        public static string PluginUpdateAvailable_Title {
            get {
                return ResourceManager.GetString("PluginUpdateAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Updater ähnelt.
        /// </summary>
        public static string PluginUpdater_Title {
            get {
                return ResourceManager.GetString("PluginUpdater_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ArmA Path ähnelt.
        /// </summary>
        public static string Prop_ArmAPath {
            get {
                return ResourceManager.GetString("Prop_ArmAPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Type ähnelt.
        /// </summary>
        public static string Prop_ProjectType {
            get {
                return ResourceManager.GetString("Prop_ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Properties_General_Language {
            get {
                return ResourceManager.GetString("Properties_General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string PropertiesDialog_Header {
            get {
                return ResourceManager.GetString("PropertiesDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string PropertiesDialog_Title {
            get {
                return ResourceManager.GetString("PropertiesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Reporting ähnelt.
        /// </summary>
        public static string Property_General_ErrorReporting {
            get {
                return ResourceManager.GetString("Property_General_ErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Report Exceptions ähnelt.
        /// </summary>
        public static string Property_General_ErrorReporting_AutoReportException {
            get {
                return ResourceManager.GetString("Property_General_ErrorReporting_AutoReportException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating ähnelt.
        /// </summary>
        public static string Property_General_Updating {
            get {
                return ResourceManager.GetString("Property_General_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Auto-Plugin-Update at start ähnelt.
        /// </summary>
        public static string Property_General_Updating_EnableAutoPluginsUpdateAtStart {
            get {
                return ResourceManager.GetString("Property_General_Updating_EnableAutoPluginsUpdateAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Auto-Tool-Update at start ähnelt.
        /// </summary>
        public static string Property_General_Updating_EnableAutoToolUpdateAtStart {
            get {
                return ResourceManager.GetString("Property_General_Updating_EnableAutoToolUpdateAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use InDev Builds ähnelt.
        /// </summary>
        public static string Property_General_Updating_UseInDevBuilds {
            get {
                return ResourceManager.GetString("Property_General_Updating_UseInDevBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please tell us what happened ähnelt.
        /// </summary>
        public static string ReportDialog_Header {
            get {
                return ResourceManager.GetString("ReportDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error Report Dialog ähnelt.
        /// </summary>
        public static string ReportDialog_Title {
            get {
                return ResourceManager.GetString("ReportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rescan Workspace ähnelt.
        /// </summary>
        public static string RescanWorkspace {
            get {
                return ResourceManager.GetString("RescanWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Search_Close {
            get {
                return ResourceManager.GetString("Search_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find ähnelt.
        /// </summary>
        public static string Search_CueFindText {
            get {
                return ResourceManager.GetString("Search_CueFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        /// </summary>
        public static string Search_CueReplaceText {
            get {
                return ResourceManager.GetString("Search_CueReplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Case Sensitive ähnelt.
        /// </summary>
        public static string Search_IsCaseSensitive {
            get {
                return ResourceManager.GetString("Search_IsCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match Whole Word ähnelt.
        /// </summary>
        public static string Search_MatchWholeWord {
            get {
                return ResourceManager.GetString("Search_MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find Next ähnelt.
        /// </summary>
        public static string Search_Next {
            get {
                return ResourceManager.GetString("Search_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace All ähnelt.
        /// </summary>
        public static string Search_ReplaceAll {
            get {
                return ResourceManager.GetString("Search_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace Next ähnelt.
        /// </summary>
        public static string Search_ReplaceNext {
            get {
                return ResourceManager.GetString("Search_ReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Regex ähnelt.
        /// </summary>
        public static string Search_UseRegex {
            get {
                return ResourceManager.GetString("Search_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Document ähnelt.
        /// </summary>
        public static string SearchModeCurrentDocument {
            get {
                return ResourceManager.GetString("SearchModeCurrentDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Project ähnelt.
        /// </summary>
        public static string SearchModeCurrentProject {
            get {
                return ResourceManager.GetString("SearchModeCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entire Solution ähnelt.
        /// </summary>
        public static string SearchModeEntireSolution {
            get {
                return ResourceManager.GetString("SearchModeEntireSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Documents ähnelt.
        /// </summary>
        public static string SearchModeOpenDocuments {
            get {
                return ResourceManager.GetString("SearchModeOpenDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show output from: ähnelt.
        /// </summary>
        public static string ShowOutputFromSource {
            get {
                return ResourceManager.GetString("ShowOutputFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a new update available for ArmA.Studio.
        ///Current Version: {0}
        ///New Version {1}
        ///
        ///Do you want to update now? ähnelt.
        /// </summary>
        public static string SoftwareUpdateAvailable_Body {
            get {
                return ResourceManager.GetString("SoftwareUpdateAvailable_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software update {0} Available ähnelt.
        /// </summary>
        public static string SoftwareUpdateAvailable_Title {
            get {
                return ResourceManager.GetString("SoftwareUpdateAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provided value contains invalid characters ähnelt.
        /// </summary>
        public static string SolutionFile_NameContainsInvalidFiles {
            get {
                return ResourceManager.GetString("SolutionFile_NameContainsInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applying available plugin updates ähnelt.
        /// </summary>
        public static string Splash_ApplyingPossiblyAvailablePluginUpdates {
            get {
                return ResourceManager.GetString("Splash_ApplyingPossiblyAvailablePluginUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for plugin&lt;{0}&gt; update ähnelt.
        /// </summary>
        public static string Splash_CheckingForPluginXUpdate {
            get {
                return ResourceManager.GetString("Splash_CheckingForPluginXUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for tool updates ähnelt.
        /// </summary>
        public static string Splash_CheckingForToolUpdates {
            get {
                return ResourceManager.GetString("Splash_CheckingForToolUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doing Initial Lint {0}/{1} &apos;{2}&apos; ähnelt.
        /// </summary>
        public static string Splash_DoingInitialLint {
            get {
                return ResourceManager.GetString("Splash_DoingInitialLint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Breakpoints ähnelt.
        /// </summary>
        public static string Splash_LoadingBreakpointInformations {
            get {
                return ResourceManager.GetString("Splash_LoadingBreakpointInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Plugins ähnelt.
        /// </summary>
        public static string Splash_LoadingPlugins {
            get {
                return ResourceManager.GetString("Splash_LoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Plugin &apos;{0}&apos; is blocked due to being downloaded from the internet.
        ///To unblock this file, user action is required.
        ///
        ///Please manually navigate into the &apos;Plugins&apos; folder of ArmA.Studio, open the file properties and click &apos;Approve&apos; (at the very bottom)
        ///In case that does not fixes the problem, please get in contact via Discord. ähnelt.
        /// </summary>
        public static string Splash_LoadUnsafeException_Body {
            get {
                return ResourceManager.GetString("Splash_LoadUnsafeException_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Blocked ähnelt.
        /// </summary>
        public static string Splash_LoadUnsafeException_Title {
            get {
                return ResourceManager.GetString("Splash_LoadUnsafeException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preparing Solution ähnelt.
        /// </summary>
        public static string Splash_PreparingSolution {
            get {
                return ResourceManager.GetString("Splash_PreparingSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching Solution File ähnelt.
        /// </summary>
        public static string Splash_SearchingSolutionFile {
            get {
                return ResourceManager.GetString("Splash_SearchingSolutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setting Workspace ähnelt.
        /// </summary>
        public static string Splash_SettingWorkspace {
            get {
                return ResourceManager.GetString("Splash_SettingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update available ähnelt.
        /// </summary>
        public static string Splash_UpdateAvailable {
            get {
                return ResourceManager.GetString("Splash_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unavailable ähnelt.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating ähnelt.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string VariableName {
            get {
                return ResourceManager.GetString("VariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to load existing watch entries. ähnelt.
        /// </summary>
        public static string VariablesView_FailedToLoadExistingWatchEntries {
            get {
                return ResourceManager.GetString("VariablesView_FailedToLoadExistingWatchEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string VariableValue {
            get {
                return ResourceManager.GetString("VariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string VariableValueType {
            get {
                return ResourceManager.GetString("VariableValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whoops ähnelt.
        /// </summary>
        public static string Whoops {
            get {
                return ResourceManager.GetString("Whoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_Browse {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the folder where the project is located. ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_Description {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace Setup ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_Header {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Workspace path is a simple folder where ArmA.Studio is saving some files related to the tool.
        ///For addon development, it is best placed in your &apos;@mod/Addons&apos;.
        ///For mission development, it should be placed in the folder above your mission files:
        ///&apos;C:\Users\&lt;Username&gt;\Documents\Arma 3\missions\&apos; ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_Help_Body {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Help_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where to place this path at? ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_Help_Header {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Help_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a valid workspace ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_NoWorkspaceSelected {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_NoWorkspaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_SelectPrev {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_SelectPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workspace Dialog ähnelt.
        /// </summary>
        public static string WorkspaceSelectorDialog_Title {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading &apos;{0}&apos;
        ///&apos;{1}&apos; was thrown.
        ///
        ///{2} ähnelt.
        /// </summary>
        public static string XSHD_Loading_Error_Body {
            get {
                return ResourceManager.GetString("XSHD_Loading_Error_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XSHD Syntax file loading failed. ähnelt.
        /// </summary>
        public static string XSHD_Loading_Error_Title {
            get {
                return ResourceManager.GetString("XSHD_Loading_Error_Title", resourceCulture);
            }
        }
    }
}
