//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmA.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArmA.Studio.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes you made require a restart.
        ///Do you want to restart now?.
        /// </summary>
        public static string ChangesRequireRestart_Body {
            get {
                return ResourceManager.GetString("ChangesRequireRestart_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Required.
        /// </summary>
        public static string ChangesRequireRestart_Title {
            get {
                return ResourceManager.GetString("ChangesRequireRestart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the UI-Main config entry.
        /// </summary>
        public static string ConfigEntrySelectorDialog_Header {
            get {
                return ResourceManager.GetString("ConfigEntrySelectorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI-Config Selector.
        /// </summary>
        public static string ConfigEntrySelectorDialog_Title {
            get {
                return ResourceManager.GetString("ConfigEntrySelectorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose File Type.
        /// </summary>
        public static string CreateNewFileDialog_Header {
            get {
                return ResourceManager.GetString("CreateNewFileDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        public static string CreateNewFileDialog_Title {
            get {
                return ResourceManager.GetString("CreateNewFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Debugger_Continue {
            get {
                return ResourceManager.GetString("Debugger_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the execution wherever it currently is..
        /// </summary>
        public static string Debugger_Pause_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Pause_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Debugger_Start {
            get {
                return ResourceManager.GetString("Debugger_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step into current scope.
        /// </summary>
        public static string Debugger_StepInto_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepInto_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step out of current scope.
        /// </summary>
        public static string Debugger_StepOut_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step over command.
        /// </summary>
        public static string Debugger_StepOver_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_StepOver_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaches the debugger and stops the debugging session..
        /// </summary>
        public static string Debugger_Stop_Tooltip {
            get {
                return ResourceManager.GetString("Debugger_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current document contains unsaved changes.
        ///Do you want to save before close?.
        /// </summary>
        public static string DocumentBase_CloseSaveConfirmation_Body {
            get {
                return ResourceManager.GetString("DocumentBase_CloseSaveConfirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Data.
        /// </summary>
        public static string DocumentBase_CloseSaveConfirmation_Caption {
            get {
                return ResourceManager.GetString("DocumentBase_CloseSaveConfirmation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Item....
        /// </summary>
        public static string ExistingItem {
            get {
                return ResourceManager.GetString("ExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Infos {
            get {
                return ResourceManager.GetString("Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string LicenseViewer_Header {
            get {
                return ResourceManager.GetString("LicenseViewer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Viewer.
        /// </summary>
        public static string LicenseViewer_Title {
            get {
                return ResourceManager.GetString("LicenseViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string MenuItem_Licenses {
            get {
                return ResourceManager.GetString("MenuItem_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Panels.
        /// </summary>
        public static string MenuItem_Panels {
            get {
                return ResourceManager.GetString("MenuItem_Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string MenuItem_Properties {
            get {
                return ResourceManager.GetString("MenuItem_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MenuItem_Quit {
            get {
                return ResourceManager.GetString("MenuItem_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuItem_Save {
            get {
                return ResourceManager.GetString("MenuItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string MenuItem_SaveAll {
            get {
                return ResourceManager.GetString("MenuItem_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch _Workspace.
        /// </summary>
        public static string MenuItem_SwitchWorkspace {
            get {
                return ResourceManager.GetString("MenuItem_SwitchWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file &apos;{0}&apos;?.
        /// </summary>
        public static string MessageBoxDeleteFileConfirmation_Body {
            get {
                return ResourceManager.GetString("MessageBoxDeleteFileConfirmation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Delete Confirmation.
        /// </summary>
        public static string MessageBoxDeleteFileConfirmation_Title {
            get {
                return ResourceManager.GetString("MessageBoxDeleteFileConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has changed outside of the studio.
        ///Do you want to reload?
        ///Current progress will be lost..
        /// </summary>
        public static string MessageBoxFileChanged_Body {
            get {
                return ResourceManager.GetString("MessageBoxFileChanged_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Has Changed.
        /// </summary>
        public static string MessageBoxFileChanged_Title {
            get {
                return ResourceManager.GetString("MessageBoxFileChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed with &apos;{0}&apos;
        ///{1}
        ///{2}.
        /// </summary>
        public static string MessageBoxOperationFailed_Body {
            get {
                return ResourceManager.GetString("MessageBoxOperationFailed_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string MessageBoxOperationFailed_Title {
            get {
                return ResourceManager.GetString("MessageBoxOperationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item....
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the current document, there is no config entry available the UI-View could be generated from..
        /// </summary>
        public static string NoConfigPresent_Body {
            get {
                return ResourceManager.GetString("NoConfigPresent_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Config Entry.
        /// </summary>
        public static string NoConfigPresent_Title {
            get {
                return ResourceManager.GetString("NoConfigPresent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in File Explorer.
        /// </summary>
        public static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Output_ClearAllToolTip {
            get {
                return ResourceManager.GetString("Output_ClearAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        public static string PanelDisplayName_ErrorList {
            get {
                return ResourceManager.GetString("PanelDisplayName_ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string PanelDisplayName_Output {
            get {
                return ResourceManager.GetString("PanelDisplayName_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PanelDisplayName_Properties {
            get {
                return ResourceManager.GetString("PanelDisplayName_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string PanelDisplayName_Solution {
            get {
                return ResourceManager.GetString("PanelDisplayName_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan Workspace.
        /// </summary>
        public static string RescanWorkspace {
            get {
                return ResourceManager.GetString("RescanWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show output from:.
        /// </summary>
        public static string ShowOutputFromSource {
            get {
                return ResourceManager.GetString("ShowOutputFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided value contains invalid characters.
        /// </summary>
        public static string SolutionFile_NameContainsInvalidFiles {
            get {
                return ResourceManager.GetString("SolutionFile_NameContainsInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops.
        /// </summary>
        public static string Whoops {
            get {
                return ResourceManager.GetString("Whoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Existing.
        /// </summary>
        public static string WorkspaceSelectorDialog_Browse {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder where the project is located..
        /// </summary>
        public static string WorkspaceSelectorDialog_Description {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Setup.
        /// </summary>
        public static string WorkspaceSelectorDialog_Header {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid workspace.
        /// </summary>
        public static string WorkspaceSelectorDialog_NoWorkspaceSelected {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_NoWorkspaceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Dialog.
        /// </summary>
        public static string WorkspaceSelectorDialog_Title {
            get {
                return ResourceManager.GetString("WorkspaceSelectorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading &apos;{0}&apos;
        ///&apos;{1}&apos; was thrown.
        ///
        ///{2}.
        /// </summary>
        public static string XSHD_Loading_Error_Body {
            get {
                return ResourceManager.GetString("XSHD_Loading_Error_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSHD Syntax file loading failed..
        /// </summary>
        public static string XSHD_Loading_Error_Title {
            get {
                return ResourceManager.GetString("XSHD_Loading_Error_Title", resourceCulture);
            }
        }
    }
}
