//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma.Studio.UiEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arma.Studio.UiEditor.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVETEXT.
        /// </summary>
        public static string CT_ACTIVETEXT {
            get {
                return ResourceManager.GetString("CT_ACTIVETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANIMATED TEXTURE.
        /// </summary>
        public static string CT_ANIMATED_TEXTURE {
            get {
                return ResourceManager.GetString("CT_ANIMATED_TEXTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUTTON.
        /// </summary>
        public static string CT_BUTTON {
            get {
                return ResourceManager.GetString("CT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKBOX.
        /// </summary>
        public static string CT_CHECKBOX {
            get {
                return ResourceManager.GetString("CT_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECKBOXES.
        /// </summary>
        public static string CT_CHECKBOXES {
            get {
                return ResourceManager.GetString("CT_CHECKBOXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBO.
        /// </summary>
        public static string CT_COMBO {
            get {
                return ResourceManager.GetString("CT_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTEXT MENU.
        /// </summary>
        public static string CT_CONTEXT_MENU {
            get {
                return ResourceManager.GetString("CT_CONTEXT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLS GROUP.
        /// </summary>
        public static string CT_CONTROLS_GROUP {
            get {
                return ResourceManager.GetString("CT_CONTROLS_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLS TABLE.
        /// </summary>
        public static string CT_CONTROLS_TABLE {
            get {
                return ResourceManager.GetString("CT_CONTROLS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string CT_EDIT {
            get {
                return ResourceManager.GetString("CT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HITZONES.
        /// </summary>
        public static string CT_HITZONES {
            get {
                return ResourceManager.GetString("CT_HITZONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string CT_HTML {
            get {
                return ResourceManager.GetString("CT_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITEMSLOT.
        /// </summary>
        public static string CT_ITEMSLOT {
            get {
                return ResourceManager.GetString("CT_ITEMSLOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINEBREAK.
        /// </summary>
        public static string CT_LINEBREAK {
            get {
                return ResourceManager.GetString("CT_LINEBREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTBOX.
        /// </summary>
        public static string CT_LISTBOX {
            get {
                return ResourceManager.GetString("CT_LISTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTNBOX.
        /// </summary>
        public static string CT_LISTNBOX {
            get {
                return ResourceManager.GetString("CT_LISTNBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISTNBOX CHECKABLE.
        /// </summary>
        public static string CT_LISTNBOX_CHECKABLE {
            get {
                return ResourceManager.GetString("CT_LISTNBOX_CHECKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        public static string CT_MAP {
            get {
                return ResourceManager.GetString("CT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP MAIN.
        /// </summary>
        public static string CT_MAP_MAIN {
            get {
                return ResourceManager.GetString("CT_MAP_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string CT_MENU {
            get {
                return ResourceManager.GetString("CT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU STRIP.
        /// </summary>
        public static string CT_MENU_STRIP {
            get {
                return ResourceManager.GetString("CT_MENU_STRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT.
        /// </summary>
        public static string CT_OBJECT {
            get {
                return ResourceManager.GetString("CT_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT CONT ANIM.
        /// </summary>
        public static string CT_OBJECT_CONT_ANIM {
            get {
                return ResourceManager.GetString("CT_OBJECT_CONT_ANIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT CONTAINER.
        /// </summary>
        public static string CT_OBJECT_CONTAINER {
            get {
                return ResourceManager.GetString("CT_OBJECT_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECT ZOOM.
        /// </summary>
        public static string CT_OBJECT_ZOOM {
            get {
                return ResourceManager.GetString("CT_OBJECT_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRESS.
        /// </summary>
        public static string CT_PROGRESS {
            get {
                return ResourceManager.GetString("CT_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHORTCUTBUTTON.
        /// </summary>
        public static string CT_SHORTCUTBUTTON {
            get {
                return ResourceManager.GetString("CT_SHORTCUTBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIDER.
        /// </summary>
        public static string CT_SLIDER {
            get {
                return ResourceManager.GetString("CT_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATIC.
        /// </summary>
        public static string CT_STATIC {
            get {
                return ResourceManager.GetString("CT_STATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATIC SKEW.
        /// </summary>
        public static string CT_STATIC_SKEW {
            get {
                return ResourceManager.GetString("CT_STATIC_SKEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRUCTURED TEXT.
        /// </summary>
        public static string CT_STRUCTURED_TEXT {
            get {
                return ResourceManager.GetString("CT_STRUCTURED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOOLBOX.
        /// </summary>
        public static string CT_TOOLBOX {
            get {
                return ResourceManager.GetString("CT_TOOLBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREE.
        /// </summary>
        public static string CT_TREE {
            get {
                return ResourceManager.GetString("CT_TREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string CT_USER {
            get {
                return ResourceManager.GetString("CT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLE DIRECTION.
        /// </summary>
        public static string CT_VEHICLE_DIRECTION {
            get {
                return ResourceManager.GetString("CT_VEHICLE_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLETOGGLES.
        /// </summary>
        public static string CT_VEHICLETOGGLES {
            get {
                return ResourceManager.GetString("CT_VEHICLETOGGLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBUTTON.
        /// </summary>
        public static string CT_XBUTTON {
            get {
                return ResourceManager.GetString("CT_XBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCOMBO.
        /// </summary>
        public static string CT_XCOMBO {
            get {
                return ResourceManager.GetString("CT_XCOMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XKEYDESC.
        /// </summary>
        public static string CT_XKEYDESC {
            get {
                return ResourceManager.GetString("CT_XKEYDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLISTBOX.
        /// </summary>
        public static string CT_XLISTBOX {
            get {
                return ResourceManager.GetString("CT_XLISTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLIDER.
        /// </summary>
        public static string CT_XSLIDER {
            get {
                return ResourceManager.GetString("CT_XSLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string InterfaceSize_Large {
            get {
                return ResourceManager.GetString("InterfaceSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string InterfaceSize_Normal {
            get {
                return ResourceManager.GetString("InterfaceSize_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string InterfaceSize_Small {
            get {
                return ResourceManager.GetString("InterfaceSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Large.
        /// </summary>
        public static string InterfaceSize_VeryLarge {
            get {
                return ResourceManager.GetString("InterfaceSize_VeryLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Small.
        /// </summary>
        public static string InterfaceSize_VerySmall {
            get {
                return ResourceManager.GetString("InterfaceSize_VerySmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI-Editor.
        /// </summary>
        public static string LoggerName {
            get {
                return ResourceManager.GetString("LoggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string UiEditor_Background {
            get {
                return ResourceManager.GetString("UiEditor_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Background displayed in the canvas area..
        /// </summary>
        public static string UiEditor_Background_ToolTip {
            get {
                return ResourceManager.GetString("UiEditor_Background_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gridsize.
        /// </summary>
        public static string UiEditor_CanvasGridSize {
            get {
                return ResourceManager.GetString("UiEditor_CanvasGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the snap-grid..
        /// </summary>
        public static string UiEditor_CanvasGridSize_ToolTip {
            get {
                return ResourceManager.GetString("UiEditor_CanvasGridSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIEditor.
        /// </summary>
        public static string UIEditor_Document {
            get {
                return ResourceManager.GetString("UIEditor_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the following classes: {0}.
        /// </summary>
        public static string UiEditor_FailedToLoad_Body_0names {
            get {
                return ResourceManager.GetString("UiEditor_FailedToLoad_Body_0names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load all classes.
        /// </summary>
        public static string UiEditor_FailedToLoad_Caption {
            get {
                return ResourceManager.GetString("UiEditor_FailedToLoad_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load config..
        /// </summary>
        public static string UiEditor_FailedToLoadConfig_Body {
            get {
                return ResourceManager.GetString("UiEditor_FailedToLoadConfig_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        public static string UiEditor_FailedToLoadConfig_Caption {
            get {
                return ResourceManager.GetString("UiEditor_FailedToLoadConfig_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string UiEditor_Height {
            get {
                return ResourceManager.GetString("UiEditor_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport Height.
        /// </summary>
        public static string UiEditor_Height_ToolTip {
            get {
                return ResourceManager.GetString("UiEditor_Height_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight all.
        /// </summary>
        public static string UiEditor_HighlightAll {
            get {
                return ResourceManager.GetString("UiEditor_HighlightAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights all control elements by drawing a box around them..
        /// </summary>
        public static string UiEditor_HighlightAll_ToolTip {
            get {
                return ResourceManager.GetString("UiEditor_HighlightAll_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Size.
        /// </summary>
        public static string UiEditor_InterfaceSize {
            get {
                return ResourceManager.GetString("UiEditor_InterfaceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arma.Studio - UIEditor.
        /// </summary>
        public static string UIEditor_Name {
            get {
                return ResourceManager.GetString("UIEditor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string UIEditor_Toolbox {
            get {
                return ResourceManager.GetString("UIEditor_Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string UiEditor_Width {
            get {
                return ResourceManager.GetString("UiEditor_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport Width..
        /// </summary>
        public static string UiEditor_Width_ToolTip {
            get {
                return ResourceManager.GetString("UiEditor_Width_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string UiEditor_Zoom {
            get {
                return ResourceManager.GetString("UiEditor_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zoom value..
        /// </summary>
        public static string UiEditor_Zoom_ToolTip {
            get {
                return ResourceManager.GetString("UiEditor_Zoom_ToolTip", resourceCulture);
            }
        }
    }
}
